import streamlit as st
from db import get_lectures  # Import the function to retrieve lecture PDFs from the database
import pandas as pd
import openai  # Library to interact with GPT-4o mini API

# Set up OpenAI API key
openai.api_key = ""  # Replace with your OpenAI API key or use environment variable

def generate_quiz(pdf_title):
    """
    Generate a quiz with 10 questions (MCQ and True/False) using GPT-4o mini.
    Args:
        pdf_title (str): Title of the selected PDF (used as context placeholder).
    Returns:
        str: The quiz questions generated by GPT-4o mini.
    """
    try:
        response = openai.ChatCompletion.create(
            model="gpt-4o",  # Use GPT-4o mini model
            messages=[
                {"role": "system", "content": "You are a quiz generator assistant. Generate 10 quiz questions based on the given lecture title. Include multiple-choice questions (with 4 options) and True/False questions. Provide answers for each question at the end."},
                {"role": "user", "content": f"Generate a 10-question quiz based on the lecture titled: '{pdf_title}'"}
            ],
            max_tokens=800
        )
        return response["choices"][0]["message"]["content"]
    except Exception as e:
        return f"Error generating quiz: {e}"

def quiz_generation():
    # Header for the Quiz Generation section
    st.markdown('<div class="lecture-header">Quiz</div>', unsafe_allow_html=True)

    # Fetch the list of uploaded lecture PDFs from the database
    lectures = get_lectures()
    if not lectures:
        st.write("No lecture summaries available for quiz generation.")
        return

    # Convert the lecture data to a DataFrame for easy selection
    lecture_data = pd.DataFrame(lectures, columns=["ID", "Title", "Upload Date", "File Path"])

    # Dropdown for selecting a lecture PDF
    lecture_titles = lecture_data["Title"].tolist()
    selected_lecture_title = st.selectbox("Select a lecture to generate a quiz:", lecture_titles)

    # Button to generate a quiz using GPT-4o mini
    if st.button("Generate Quiz"):
        st.markdown("### Generating Quiz...")
        with st.spinner("Generating the quiz..."):
            quiz = generate_quiz(selected_lecture_title)
        st.markdown("### Quiz Questions:")
        st.write(quiz)

# Run the quiz generation function
if __name__ == "__main__":
    quiz_generation()
